### ISSUE TITLE
[suggestion] config for insanity killing the player

### ISSUE THREAD

**Issue by someDudeeeee** [ChampionAsh5357/Paranoia#6]
why does insanity even kill the player in the first place?
there should be a toggle for it, especially since players who have no clue what the sanity system is will usually just end up dying to it and it discourages exploring unless you have a crap ton of torches

**Comment by ChampionAsh5357** [comment]
That's basically the whole idea of the mod. You don't know what sanity is or how it works. Your objective is to figure out how to best survive with the sanity. The mod was made like this to emulate that feeling of insanity. It might be annoying, but that was the point. There are many other ways to better handle sanity and as such can increase how long sanity might take to tick to increasing sanity at some exorbitant rate.

If you would like to suggest an alternative that would punish the player for not actively maintaining their sanity, I'll be happy to take it into consideration and add a configuration. But otherwise, this mod was made for the express purpose of making people go insane whether that be from scary or annoyance. I'll leave this open until you respond.

**Comment by someDudeeeee** [comment]
Instead of just killing players, I think that the effects of insanity should appear at an increased rate depending on how long you are insane for until the point where it happens almost every other second with each different effect transitioning in and out randomly. Also, a side note I would like to suggest adding more "ghost" mobs but they actually follow you around and just kinda stalk you.

The only reason why I dont like how insanity just kills the player is because death is too easy of a way out of the insanity at least in my opinion. There is no penalty for death other than losing your items, and if you plan your suicide properly then you can continue almost as if nothing had happened to begin with, youl only be losing a few xp levels which can be easily accounted for with a mob farm.

**Comment by ChampionAsh5357** [comment]
I should explain how the implementation works. Currently, what you are describing is implemented in a sort of roundabout way. Every time you die, the amount of sanity you can have at any point decreases by a fixed number. The more you die, the faster it is to lose sanity as you start closer to the minimum value before sanity starts to kill you. So, there is a penalty.

As for the above mentioned tactic, many of the effects minimize the amount of lag because of how little they are normally called. If I were to start pushing effects every second, it would be impossible for the player to be controllable in any regard as most of them effect the player in stages, hence why I broke it down into a sort of three phase sanity: normal, hiding, and running.

So, all in all, death does punish the player by lowering their max sanity, and there are ways to recover it that makes the system balanced. Personally, Minecraft supports that mindset where proper suicide pretty much as no effect if positioned properly, and I cannot account for all the ways where it would cause some sort of exploit with my mod. That's my reasoning for not adding a config option for this at the current moment. 

As for another reason, currently the mod is optimized in its 'current' format, but it still causes a bit of lag due to some implementation bugs. I have recently bought a new computer because my old one had a water accident, so I want to reprogram the mods from scratch to better implement cleaner and more efficient practices. Because of that, most of my systems are being redone to better suit its overall goal. However, this will probably take much longer to create because of this. That's more or less the reason why there is only a single 'ghost' mob format within the game.

**Comment by someDudeeeee** [comment]
oh ok, thanks for the explanation
